language: python
python:
  - "3.8"
os: linux
services:
  - postgresql
env:
  global:
    - DEPS_DIR=$HOME/dependencies
  matrix:
    - WITH_TA_LIBRARY=yes
      TA_INCLUDE_PATH=$DEPS_DIR/include
      LD_LIBRARY_PATH=$DEPS_DIR/lib
      TA_LIBRARY_PATH=$DEPS_DIR/lib
cache:
  directories:
    - $DEPS_DIR
install:
  - pip install --upgrade pip wheel
  - pip install coverage
  - if [ $WITH_TA_LIBRARY = "yes" ]; then
      ./tools/build_talib_from_source.bash $DEPS_DIR;
    fi
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -d travis_ci_test -U postgres -f liualgotrader/setup/db-script.sql
script:
  - coverage run -m pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  username: __token__
  password:
    secure: deploy.password
  on:
    tags: true