language: python
python:
- '3.9'
os: linux
services:
- postgresql
env:
  global:
  - DEPS_DIR=$HOME/dependencies
  matrix:
  - WITH_TA_LIBRARY=yes TA_INCLUDE_PATH=$DEPS_DIR/include LD_LIBRARY_PATH=$DEPS_DIR/lib
    TA_LIBRARY_PATH=$DEPS_DIR/lib
cache:
  directories:
  - "$DEPS_DIR"
install:
- pip install --upgrade pip wheel
- pip install coverage
- pip install pytest-asyncio
- pip install pytest-timeout
- if [ $WITH_TA_LIBRARY = "yes" ]; then ./tools/build_talib_from_source.bash $DEPS_DIR;
  fi
- pip install -r liualgotrader/requirements/release.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- psql -d travis_ci_test -U postgres -f database/schema.sql
script:
- coverage run -m pytest -m "not devtest"
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  username: __token__
  password:
    secure: fZmiw6X3vh4JIoST6vOUnHqXVV6pXGKWSwmcWtoRCHJzV+fJ8QsZ+X/VuCJYkNZc6XVFJfk92QnZWTkOuUq4Y7b5wapS0/j2X1Hh7SCkslwOp9GPYIkmbVHOWfq7nrIGYghNtH+QMEX+Y8F4kFyDsqIKDydUxbGLz87HWM6swuO4Dk3ANzfCeWBvVgfraGoV5QpztDrCuDcH7N62vdhexZGtqW18n3mikxmj2XLyG+G6cM//v2wKAdEliAdRuf5OvWSYVt41W3sPc4cVSTVPjRgpyYGH6R1+QJ0daUwdRWrYXLb1vWMYfyx5kv/qViWu+zRTJyQzb3kVmXCfUs9jUzYG+lgMyi1kPxgjaNJyYHlKqot9+FslPms9Kgr7X9U+T6HeaJiEJg2dzSREYKR4XQGxw5NpCC+UajOaZ74mibrJ/usLJCrEgyegDd5glxb8XdbvEDyoNf1uxWBF2p5W/uY4K9RB0e01YJwKhF+JPoENoJhC1CsRFrIsnGah3YnU0fFX3pr5Q1yG/HQOSOFDmncEj5x6x4XQOCPKrr2X9q/XBuE1AumfJmX/XpkqjiuZLQ4hoHypwa9T5+p6PYboj0UzrA7+FZj6gw4CEi7FU+ZEPaFbUN9klVx+2UxL6L2yXKgW3rRVyulAMQUD9GTJSzC0Z/qG0mccU286o/O7nmg=
  on:
    tags: true
