language: python
python:
- '3.9'
os: linux
services:
- postgresql
env:
  global:
  - DEPS_DIR=$HOME/dependencies
  matrix:
  - WITH_TA_LIBRARY=yes TA_INCLUDE_PATH=$DEPS_DIR/include LD_LIBRARY_PATH=$DEPS_DIR/lib
    TA_LIBRARY_PATH=$DEPS_DIR/lib
cache:
  directories:
  - "$DEPS_DIR"
install:
- pip install --upgrade pip wheel
- pip install coverage
- pip install pytest-asyncio
- pip install pytest-timeout
- if [ $WITH_TA_LIBRARY = "yes" ]; then ./tools/build_talib_from_source.bash $DEPS_DIR;
  fi
- pip install -r liualgotrader/requirements/release.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- psql -d travis_ci_test -U postgres -f database/schema.sql
script:
- coverage run -m pytest -m "not devtest"
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  username: __token__
  password:
    secure: T8HRT95cQS0qDdbls94rBmlQ20liy8q+KwYQQ5MetFYxZkIr6jmc5tUcVj0ltZDmQeh5h8evUCT+KojiBkAxPuYlzFbVsmPPBMe4f1DKPo0TlWZgk8QNR8ZlDx16xaAQmuMIavFKKJSbOBLejHXkMcvM1maoE4FiPtJSZjrvvHOdaVm2OqyWLB/96QDMUaH7d24ci59/tRaTgafuOq2Xi5KS1KbsEzPAqpibU072lezzDBGDLw3PBrETm3UchS1o8SeBPA8CA20Vp7YCbK0SaJRnWcztWP7eBQDwkes6s+BmyGSaM1zwmBLQWTA3Ood5snNfnr2lgOmxfdkJ8Lxp9mDbk8zW6MgVnv/Mob9/2CkfEewvpXtRySh+X19STdCLdwlPrIYNC0X3y/nTa/RW3t9XZXn1bh+4FxoxsHqkPH5h7h7UQQO/8WXNcdTTUQGEpT2gG935AEkHoevDc8vxy7KvFozVxWtWin/BamB2/XYJ2TRw5yR/UitClA44IJHSxELWIVBUQo/Rg+tLMP/qm60r+jykJFI8YWpI12kNXmHlRBcCjd1jjP5pz0QVU1Hadyr3SEwaZ63nNmK6oIvnlOoooQYv1ysPkWd9m3kP2KR+6Lo3nFN01z/TXXAYeNMMSn18VUe6sytGPydP/aTG2zZk7KDrsvIwXNgTLfaqjRw=
  on:
    tags: true
