# This is a TOML configuration file for market_miner.py

[miners]

    #[miners.StockCluster]

    [miners.DailyOHLC]
        # symbol = ['SPY',]

        days = 60
        min_share_price = 2.0
        max_share_price = 20.0

        [miners.DailyOHLC.indicators]
            [miners.DailyOHLC.indicators.mama]
                duration = 57

