# This is a TOML configuration file.

# if set to true, allow running outside market open hours
bypass_market_schedule = false 

events = ["second", "minute", "trade", "quote"]


# ticket scanners, may have several
# scanners during the day
[scanners]
    [scanners.GoldDigger]
        filename = "/Users/amichayoren/dev/trades/scanners/gold_digger.py"
        target_strategy_name = "golden_pair"

# trading strategies, can have several *strategy* blocks
[strategies]
    # strategy class name, must implement Strategy class

    [strategies.MomentumLongV3]
        filename = "/home/amichayoren/trader/momentum_long_v3.py"

        # check_patterns = true

    [strategies.VWAPShort]
        filename = "/home/amichayoren/trader/vwap_short.py"


        # trading schedules block, trades many have
        # several windows within the same day
        [[strategies.MomentumLongV3.schedule]]
            start = 15
            duration = 60





