# This is a TOML configuration file.

# if set to true, allow running outside market open hours
<<<<<<< HEAD
bypass_market_schedule = false

# ticket scanners, may have several
# scanners during the day
[[scanners]]
=======
bypass_market_schedule = true

events = ["second", "minute", "trade", "quote"]

# ticket scanners, may have several
# scanners during the day
[scanners]
>>>>>>> 0.0.40
    [scanners.momentum]
        # check documentation for supported providers
        provider = 'polygon'

        # scan for tickers with minimal volume since day start
        min_volume = 30000

        # minimum daily percentage gap
        min_gap = 3.5

        # minimum last day dollar volume
        min_last_dv = 500000

        min_share_price = 2.0
        max_share_price = 20.0

        # How many minutes from market open, to start running scanner
        from_market_open = 15

        recurrence = 5

<<<<<<< HEAD
        # max_symbols = 440

# trading strategies, can have several *strategy* blocks
[[strategies]]
    # strategy class name, must implement Strategy class
    [strategies.MomentumLong]
        # filename = ""

        # check_patterns = true

        # trading schedules block, trades many have
        # several windows within the same day
        [[strategies.MomentumLong.schedule]]
            start = 15
            duration = 400


=======
        max_symbols = 440

# trading strategies, can have several *strategy* blocks
[strategies]
    # strategy class name, must implement Strategy class
    [strategies.VWAPShort]
        filename = "/Users/amichayoren/dev/trades/vwap_short.py"

        # trading schedules block, trades many have
        # several windows within the same day
        [[strategies.VWAPShort.schedule]]
            start = 15
            duration = 60
    [strategies.MomentumLongV3]
        filename = "/Users/amichayoren/dev/trades/momentum_long_v3.py"

        # trading schedules block, trades many have
        # several windows within the same day
        [[strategies.MomentumLongV3.schedule]]
            start = 15
            duration = 60
>>>>>>> 0.0.40



