# This is a TOML configuration file for market_miner.py

[miners]

    [miners.StockCluster]

    [miners.DailyOHLC]
        filename = "<select-path>/daily_ohlc.py"
        # to follow specific symbols
        # symbol = ['SPY',]

        days = 60

        [miners.DailyOHLC.indicators]
            [miners.DailyOHLC.indicators.mama]


